# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

locale: pt-PT

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Priscila Silveira Nails
email: priscilanailsgel@gmail.com
description: "Cuidar das suas unhas é cuidar de você.\n
Profissional com anos de experiência em nail design, verniz de gel, gelinho, alongamento em fibra, banho de gel e decoração e manutenção de unhas em geral. Agende já o seu horário."
# twitter_username: username
# github_username: username
minimal_mistakes_skin: default
search: false

repository: andresilveirah/priscilasilveiranails

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Priscila Silveira"
  avatar : "/assets/images/bio-photo.webp"
  bio    : "Formada em Nail Designing no Brasil.\nApaixonada por unhas lindas."
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/priscilasilveiranails"
    - label: "WhatsApp"
      icon: "fab fa-fw fa-whatsapp"
      url: "https://api.whatsapp.com/send?phone=351961581916"
    - label: "961 581 916"
      icon: "fa fa-fw fa-phone"
      url: "tel:+351961581916"

footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/priscilasilveiranails"
    - label: "WhatsApp"
      icon: "fab fa-fw fa-whatsapp"
      url: "https://api.whatsapp.com/send?phone=351961581916"
    - label: "961 581 916"
      icon: "fa fa-fw fa-phone"
      url: "tel:+351961581916"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
